### ISSUE TITLE
Tried building neosurf from source, errors occured

### ISSUE THREAD

**Issue by FrostKnight** [CobaltBSD/neosurf#17] opened 2023-08-02 01:55 UTC
I got to 73% completion and then saw this:

/home/localuser/Downloads/neosurf/src/content/handlers/javascript/duktape/dukky.c:40:10: fatal error: duktape/binding.h: No such file or directory
 #include "duktape/binding.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/neosurf.dir/build.make:1000: src/CMakeFiles/neosurf.dir/content/handlers/javascript/duktape/dukky.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:511: src/CMakeFiles/neosurf.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

Btw, using Hyperbola GNU/Linux-Libre

**Comment by CobaltBSD** [comment] 2023-08-05 06:33
Please clone the repository and try again, and let me know if you get an error/which one you get.

**Comment by FrostKnight** [comment] 2023-08-05 23:57
> Please clone the repository and try again, and let me know if you get an error/which one you get.
git clone https://github.com/CobaltBSD/neosurf
cd neosurf/neosurf
mkdir -v build 
cd build
then this:

doas cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DNEOSURF_BUILD_VI_FRONTEND=OFF
yacc program found: bison
-- Configuring done
-- Generating done
-- Build files have been written to: /home/youruser/neosurf/build/contrib/libcss/gen_parser
make: Entering directory '/home/youruser/neosurf/build/contrib/libcss/gen_parser'
make[1]: Entering directory '/home/youruser/neosurf/build/contrib/libcss/gen_parser'
make[2]: Entering directory '/home/youruser/neosurf/build/contrib/libcss/gen_parser'
make[2]: Leaving directory '/home/youruser/neosurf/build/contrib/libcss/gen_parser'
[100%] Built target gen_parser
make[1]: Leaving directory '/home/youruser/neosurf/build/contrib/libcss/gen_parser'
make: Leaving directory '/home/youruser/neosurf/build/contrib/libcss/gen_parser'
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'libxml-2.0'
--   Found libxml-2.0, version 2.9.10
-- Checking for module 'libjpeg'
--   Found libjpeg, version 2.0.5
-- Checking for module 'libpng'
--   Found libpng, version 1.6.37
-- Checking for module 'libcurl'
--   Found libcurl, version 7.72.0
-- Checking for module 'libcrypto'
--   Found libcrypto, version 3.2.6
-- Checking for module 'libpsl'
--   Found libpsl, version 0.21.0
-- Checking for module 'libwebp'
--   Found libwebp, version 0.6.1
-- Checking for module 'zlib'
--   Found zlib, version 1.2.11
-- Checking for module 'libssl'
--   Found libssl, version 3.2.6
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
bison: unrecognized option '--header=/home/youruser/neosurf/build/contrib/nsgenbind/nsgenbind-parser.h'
Try 'bison --help' for more information.
CMake Error at CMakeLists.txt:17 (message):
  yacc nsgenbind failed (error 1)


-- Configuring incomplete, errors occurred!
See also "/home/youruser/neosurf/build/contrib/nsgenbind/CMakeFiles/CMakeOutput.log".
CMake Error at src/CMakeLists.txt:47 (message):
  nsgenbind configure failed (error 1)


-- Configuring incomplete, errors occurred!
See also "/home/youruser/neosurf/build/CMakeFiles/CMakeOutput.log".


I don't know why nsgenbind configure failure happened either. I have that package installed in my OS.

**Comment by CobaltBSD** [comment] 2023-08-07 03:22
I know what the issue is now, but I've been unable to reproduce it on my own machine. Can you try cloning the repo and building again? Please let me know if it's fixed or you get another error.

**Comment by FrostKnight** [comment] 2023-08-07 03:58
> I know what the issue is now, but I've been unable to reproduce it on my own machine. Can you try cloning the repo and building again? Please let me know if it's fixed or you get another error.

Hmm... got this error this time:

cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DNEOSURF_BUILD_VI_FRONTEND=OFF
yacc program found: bison
-- Configuring done
-- Generating done
-- Build files have been written to: /home/youruser/neosurf/build/contrib/libcss/gen_parser
make: Entering directory '/home/youruser/neosurf/build/contrib/libcss/gen_parser'
make[1]: Entering directory '/home/youruser/neosurf/build/contrib/libcss/gen_parser'
make[2]: Entering directory '/home/youruser/neosurf/build/contrib/libcss/gen_parser'
make[2]: Leaving directory '/home/youruser/neosurf/build/contrib/libcss/gen_parser'
[100%] Built target gen_parser
make[1]: Leaving directory '/home/youruser/neosurf/build/contrib/libcss/gen_parser'
make: Leaving directory '/home/youruser/neosurf/build/contrib/libcss/gen_parser'
bison: invalid option -- 'H'
Try 'bison --help' for more information.
CMake Error at CMakeLists.txt:17 (message):
  yacc nsgenbind failed (error 1)


-- Configuring incomplete, errors occurred!
See also "/home/youruser/neosurf/build/contrib/nsgenbind/CMakeFiles/CMakeOutput.log".
CMake Error at src/CMakeLists.txt:47 (message):
  nsgenbind configure failed (error 1)


-- Configuring incomplete, errors occurred!
See also "/home/youruser/neosurf/build/CMakeFiles/CMakeOutput.log".

**Comment by CobaltBSD** [comment] 2023-08-07 16:55
Which version of bison do you have installed?

**Comment by FrostKnight** [comment] 2023-08-07 18:37
> Which version of bison do you have installed?

3.7.5

**Comment by CobaltBSD** [comment] 2023-08-07 21:24
This problem should be fixed in the latest commit. Please let me know if you have any further issues (besides for the other one you opened, I am looking into that now).

**Comment by FrostKnight** [comment] 2023-08-08 02:04
> This problem should be fixed in the latest commit. Please let me know if you have any further issues (besides for the other one you opened, I am looking into that now).

So close, but this error came up:

[100%] Building C object frontends/gtk/CMakeFiles/neosurf-gtk.dir/hotlist.c.o
[100%] Building C object frontends/gtk/CMakeFiles/neosurf-gtk.dir/page_info.c.o
[100%] Linking C executable neosurf-gtk
/usr/bin/ld: ../../src/libneosurf.so.14: undefined reference to `RSA_get0_n'
/usr/bin/ld: ../../src/libneosurf.so.14: undefined reference to `RSA_get0_e'
collect2: error: ld returned 1 exit status
make[2]: *** [frontends/gtk/CMakeFiles/neosurf-gtk.dir/build.make:602: frontends/gtk/neosurf-gtk] Error 1
make[1]: *** [CMakeFiles/Makefile2:545: frontends/gtk/CMakeFiles/neosurf-gtk.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by CobaltBSD** [comment] 2023-08-08 17:02
The cmake command is fine, those two warnings are harmless. Are you using openssl or libressl, and what version?

**Comment by FrostKnight** [comment] 2023-08-08 17:11
> The cmake command is fine, those two warnings are harmless. Are you using openssl or libressl, and what version?

LibreSSL 3.2.8

**Comment by CobaltBSD** [comment] 2023-08-08 19:33
Compatibility with your version of LibreSSL should be fixed with the latest commit.

**Comment by FrostKnight** [comment] 2023-08-08 20:42
> Compatibility with your version of LibreSSL should be fixed with the latest commit.

Yep it does.

**Closed** 2023-08-08 20:54 UTC
